### PR TITLE
Run the initialization function only once

### LINKED ISSUE #20: Init function being run every time an item is selected
Regarding the `initializeSelectize`  function

```
 // INITIALIZE
    initializeSelectize: on('willRender', function () {
...snip...
}
```

It seems to me that this code should only be running once, and that is when the component is first initialized. But it is being called every time it is rendered. Is this intentional?

### PR DESCRIPTION
**Pull request by Ramblurr**
fixes #20

### CODE REVIEW

**Comment by yankeeinlondon** [comment]
Just wondering, do you get any deprecation warnings with this? The general rule I've been using recently is when triggering off of `didInsertElement` is to schedule it into "afterRender". This removes all deprecation notices.

**Comment by Ramblurr** [comment]
No, I haven't gotten any of those warnings with this. Though I'm on ember 2.0.2.

Hm, what do you think? Should we wrap the function's body with a call to schedule it in afterRender?

**Comment by yankeeinlondon** [comment]
Hmmmm. I suspect that they've been reducing the number of deprecations on the `didInsertElement` because when glimmer came out there was a strong reaction against this hook but it seems people have found a happy middle-ground.

Just to avoid deprecations on 1.x versions though I'd say let's wrap it for now. We can remove it once the 1.13'ers are a smaller part of the audience.

**Comment by yankeeinlondon** [comment]
```
run.schedule('afterRender', ... }
```

**Comment by yankeeinlondon** [comment]
if you want I can pull this in as-is and add the "afterRender" bit myself. easy to do now that I'm focused on this.

**Pull request merged**
