### PR TITLE
Ignore app/mirage folder on npm pack

### PR DESCRIPTION
**Pull request by kenips**
Pulling my hairs out when `animals` and `things` kept appearing in my mirage config.... anyway a bad setup of ember-cli-mirage and it's fixed in `0.2.0`.

Until `ember-cli-mirage` `0.2.0` lands though, let's keep the mirage folder out of the final pack. Note that I'm not sure if you use `npm pack`, as it [currently has a bug](https://github.com/npm/npm/issues/7030) that prevent me from adding `app/mirage` into `.npmignore`, so I've taken a slightly worse path of whitelisting folders with in `/app`. If you feel uncomfortable with this I'm open to alternatives - like taking the plunge and moving to `ember-cli-mirage` `0.2.0-beta.1` perhaps ;).

### CODE REVIEW

**Comment by yankeeinlondon** [comment]
Can you explain the problem just a bit more? Happy to accept this but feel uncomfortable at the moment because I'm not entirely sure I understand what we're avoiding.

**Comment by kenips** [comment]
The problem is that the `mirage` folder shouldn't be included in `/app` at all in the first place, as it's not something that you intend to ship (unless you're). This has been corrected in `ember-cli-mirage` `0.2.0` by moving the required folder from `/app/mirage` to `/mirage` so that Addons like yours wouldn't contaminate the App with random mirage content.

Why do we need this now, then? Well if you use `ember-cli-mirage` `0.2.0` today, you wouldn't be able to use it with any Addons that export `/app/mirage` as it take precedence over `/mirage` during initialization. So this is really fixing a corner issue of any app using `0.2.0` while the Addon is still on `0.1.x`. If you migrate your Addon to `0.2.0` we will not need this bandaid patch.

**Comment by kenips** [comment]
If it is acceptable to use `ember-cli-mirage` `0.2.0-beta.1` in this addon, I am happy to take a look and issue another PR instead of this one.

**Comment by yankeeinlondon** [comment]
Yeah i'll accept this PR now but if you'd like to push me a PR for the 0.2.0-beta I'm happy to accept that too.

**Pull request merged**
