### PR TITLE
Add support for onType Selectize Event

### PR DESCRIPTION
**Pull request by john-griffin**
onType event is fired as a text is entered. It useful when working with
Selectize fields that hit a large server side data set so that it can be
filtered as you type.

### CODE REVIEW

**Comment by yankeeinlondon** [comment]
Yes makes sense John. Not sure why I didn't include this but thanks for the PR!

**Comment by john-griffin** [comment]
:+1:

**Comment by yankeeinlondon** [comment]
available on npm as 0.1.3

**Comment by john-griffin** [comment]
Thanks for pushing that release so quickly but this commit does not appear to be in the release.

**Comment by yankeeinlondon** [comment]
oh shit ... was playing around with **gitup** for the first time might have done something silly in git. I'll get that fixed now.

**Comment by yankeeinlondon** [comment]
ok, it's in `0.1.4`

**Comment by john-griffin** [comment]
thanks that works great :smile:

**Pull request merged**
